import "@/node_modules/react-modal-video/css/modal-video.css"
import "./globals.css"
import "public/assets/css/style.css"
import "public/assets/css/responsive.css"



import 'swiper/css'
import "swiper/css/navigation"
import "swiper/css/pagination"
import 'swiper/css/free-mode';
// import {niconne, poppins, tangerine} from '@/lib/font'
import { rockwell } from "@/lib/font";
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={rockwell.variable}>
            <body>{children}</body>
        </html>
    )
}
